//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDepotDownloader_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamDepotDownloader_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Apps 的本地化字符串。
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto login failed.Use password and try again. 的本地化字符串。
        /// </summary>
        internal static string AutoLoginFailed {
            get {
                return ResourceManager.GetString("AutoLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The depot need Password. 的本地化字符串。
        /// </summary>
        internal static string BetaPasswordRequest {
            get {
                return ResourceManager.GetString("BetaPasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamDB only have Manifest History for public branch
        ///To use ManifestID for other branch, try Advanced Input 的本地化字符串。
        /// </summary>
        internal static string bnp_nomanifest {
            get {
                return ResourceManager.GetString("bnp_nomanifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache Cleared 的本地化字符串。
        /// </summary>
        internal static string CacheCleared {
            get {
                return ResourceManager.GetString("CacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Install Directory 的本地化字符串。
        /// </summary>
        internal static string ChooseInstallDirectory {
            get {
                return ResourceManager.GetString("ChooseInstallDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear File List? 的本地化字符串。
        /// </summary>
        internal static string ClearFileListQuestion {
            get {
                return ResourceManager.GetString("ClearFileListQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current ManifestID:
        ///{0} 的本地化字符串。
        /// </summary>
        internal static string CurrentManifestID {
            get {
                return ResourceManager.GetString("CurrentManifestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection to SteamDB out of time 的本地化字符串。
        /// </summary>
        internal static string dbconnectfailed {
            get {
                return ResourceManager.GetString("dbconnectfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Default) 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depot {0} not listed for app {1}  or not available on this platform 的本地化字符串。
        /// </summary>
        internal static string DepotNotListOrNotSupport {
            get {
                return ResourceManager.GetString("DepotNotListOrNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depot {0} Download Failed! 的本地化字符串。
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading File List... 的本地化字符串。
        /// </summary>
        internal static string DownloadingFileList {
            get {
                return ResourceManager.GetString("DownloadingFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depot {0} Download Successful! 的本地化字符串。
        /// </summary>
        internal static string DownloadSuccessful {
            get {
                return ResourceManager.GetString("DownloadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed To Get Manifest History! 的本地化字符串。
        /// </summary>
        internal static string FailedToGetManifestHistory {
            get {
                return ResourceManager.GetString("FailedToGetManifestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File List Loaded 的本地化字符串。
        /// </summary>
        internal static string FileListLoaded {
            get {
                return ResourceManager.GetString("FileListLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Manifest History... 的本地化字符串。
        /// </summary>
        internal static string GettingManifestHistory {
            get {
                return ResourceManager.GetString("GettingManifestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Steam login failed!Try check your account and password. 的本地化字符串。
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already Login,Do you want to logout? 的本地化字符串。
        /// </summary>
        internal static string LogoutQuestion {
            get {
                return ResourceManager.GetString("LogoutQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build ID:{0} 的本地化字符串。
        /// </summary>
        internal static string mids_BuildID {
            get {
                return ResourceManager.GetString("mids_BuildID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depot ID:{0} 的本地化字符串。
        /// </summary>
        internal static string mids_DepotID {
            get {
                return ResourceManager.GetString("mids_DepotID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Depot Name:{0} 的本地化字符串。
        /// </summary>
        internal static string mids_DepotName {
            get {
                return ResourceManager.GetString("mids_DepotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Update:{0} 的本地化字符串。
        /// </summary>
        internal static string mids_LastUpdate {
            get {
                return ResourceManager.GetString("mids_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manifest ID:{0} 的本地化字符串。
        /// </summary>
        internal static string mids_ManifestID {
            get {
                return ResourceManager.GetString("mids_ManifestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t find any depots to download for app {0} 的本地化字符串。
        /// </summary>
        internal static string NoAnyDepots {
            get {
                return ResourceManager.GetString("NoAnyDepots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No valid depot key. 的本地化字符串。
        /// </summary>
        internal static string NoDepotKey {
            get {
                return ResourceManager.GetString("NoDepotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No valid Manifest ID 的本地化字符串。
        /// </summary>
        internal static string NoManifestID {
            get {
                return ResourceManager.GetString("NoManifestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App {0} ({1}) is not available from this account. 的本地化字符串。
        /// </summary>
        internal static string NotAvailableForThisAccount {
            get {
                return ResourceManager.GetString("NotAvailableForThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Paramter! 的本地化字符串。
        /// </summary>
        internal static string ParamterError {
            get {
                return ResourceManager.GetString("ParamterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There already have a same task. 的本地化字符串。
        /// </summary>
        internal static string SameTask {
            get {
                return ResourceManager.GetString("SameTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Steam {
            get {
                object obj = ResourceManager.GetObject("Steam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap SteamGray {
            get {
                object obj = ResourceManager.GetObject("SteamGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Updating App List... 的本地化字符串。
        /// </summary>
        internal static string UpdateAppListMsg {
            get {
                return ResourceManager.GetString("UpdateAppListMsg", resourceCulture);
            }
        }
    }
}
