//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamDepotDownloader_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamDepotDownloader_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Apps.
        /// </summary>
        internal static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto login failed.Use password and try again..
        /// </summary>
        internal static string AutoLoginFailed {
            get {
                return ResourceManager.GetString("AutoLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The depot need Password..
        /// </summary>
        internal static string BetaPasswordRequest {
            get {
                return ResourceManager.GetString("BetaPasswordRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamDB only have Manifest History for public branch
        ///To use ManifestID for other branch, try Advanced Input.
        /// </summary>
        internal static string bnp_nomanifest {
            get {
                return ResourceManager.GetString("bnp_nomanifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Cleared.
        /// </summary>
        internal static string CacheCleared {
            get {
                return ResourceManager.GetString("CacheCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Install Directory.
        /// </summary>
        internal static string ChooseInstallDirectory {
            get {
                return ResourceManager.GetString("ChooseInstallDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear File List?.
        /// </summary>
        internal static string ClearFileListQuestion {
            get {
                return ResourceManager.GetString("ClearFileListQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current ManifestID:
        ///{0}.
        /// </summary>
        internal static string CurrentManifestID {
            get {
                return ResourceManager.GetString("CurrentManifestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to SteamDB out of time.
        /// </summary>
        internal static string dbconnectfailed {
            get {
                return ResourceManager.GetString("dbconnectfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Default).
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot {0} not listed for app {1}  or not available on this platform.
        /// </summary>
        internal static string DepotNotListOrNotSupport {
            get {
                return ResourceManager.GetString("DepotNotListOrNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot {0} Download Failed!.
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading File List....
        /// </summary>
        internal static string DownloadingFileList {
            get {
                return ResourceManager.GetString("DownloadingFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot {0} Download Successful!.
        /// </summary>
        internal static string DownloadSuccessful {
            get {
                return ResourceManager.GetString("DownloadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Get Manifest History!.
        /// </summary>
        internal static string FailedToGetManifestHistory {
            get {
                return ResourceManager.GetString("FailedToGetManifestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File List Loaded.
        /// </summary>
        internal static string FileListLoaded {
            get {
                return ResourceManager.GetString("FileListLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Manifest History....
        /// </summary>
        internal static string GettingManifestHistory {
            get {
                return ResourceManager.GetString("GettingManifestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input ManifesID.
        /// </summary>
        internal static string InputManifesID {
            get {
                return ResourceManager.GetString("InputManifesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Input the Cookies for SteamDB(__cfduid and cf_clearance).
        /// </summary>
        internal static string InputSteamDBCookies {
            get {
                return ResourceManager.GetString("InputSteamDBCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Cookies.
        /// </summary>
        internal static string InvalidCookies {
            get {
                return ResourceManager.GetString("InvalidCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam login failed!Try check your account and password..
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Login,Do you want to logout?.
        /// </summary>
        internal static string LogoutQuestion {
            get {
                return ResourceManager.GetString("LogoutQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build ID:{0}.
        /// </summary>
        internal static string mids_BuildID {
            get {
                return ResourceManager.GetString("mids_BuildID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot ID:{0}.
        /// </summary>
        internal static string mids_DepotID {
            get {
                return ResourceManager.GetString("mids_DepotID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depot Name:{0}.
        /// </summary>
        internal static string mids_DepotName {
            get {
                return ResourceManager.GetString("mids_DepotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update:{0}.
        /// </summary>
        internal static string mids_LastUpdate {
            get {
                return ResourceManager.GetString("mids_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest ID:{0}.
        /// </summary>
        internal static string mids_ManifestID {
            get {
                return ResourceManager.GetString("mids_ManifestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Login!.
        /// </summary>
        internal static string NeedLogin {
            get {
                return ResourceManager.GetString("NeedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any depots to download for app {0}.
        /// </summary>
        internal static string NoAnyDepots {
            get {
                return ResourceManager.GetString("NoAnyDepots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid depot key..
        /// </summary>
        internal static string NoDepotKey {
            get {
                return ResourceManager.GetString("NoDepotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamDB doesn&apos;t have the infomation of this Depot.
        /// </summary>
        internal static string nomanifesthistory {
            get {
                return ResourceManager.GetString("nomanifesthistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid Manifest ID.
        /// </summary>
        internal static string NoManifestID {
            get {
                return ResourceManager.GetString("NoManifestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App {0} ({1}) is not available from this account..
        /// </summary>
        internal static string NotAvailableForThisAccount {
            get {
                return ResourceManager.GetString("NotAvailableForThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Paramter!.
        /// </summary>
        internal static string ParamterError {
            get {
                return ResourceManager.GetString("ParamterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It may caused by invalid cookies,do you want to input new cookies?.
        /// </summary>
        internal static string refreshCookieRequest {
            get {
                return ResourceManager.GetString("refreshCookieRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There already have a same task..
        /// </summary>
        internal static string SameTask {
            get {
                return ResourceManager.GetString("SameTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Steam {
            get {
                object obj = ResourceManager.GetObject("Steam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SteamGray {
            get {
                object obj = ResourceManager.GetObject("SteamGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating App List....
        /// </summary>
        internal static string UpdateAppListMsg {
            get {
                return ResourceManager.GetString("UpdateAppListMsg", resourceCulture);
            }
        }
    }
}
